project:
  type: website
  output-dir: docs
freeze: true

website:
  title: "BSNT 2025"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: kodewil.qmd
        text: Kode Wilayah
      - href: kpm.qmd
        text: Kuesioner KPM
      - href: agen.qmd
        text: Kuesioner Agen Bank  

format:
  html:
    theme:
      - zephyr
    css: styles.css
    toc: true



